language: node_js
node_js:
- '8'
- '6'
git:
  depth: 5
cache: yarn
script:
- if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm
  run cover:lcov && cat ./coverage/lcov.info | coveralls; else npm run testonly; fi
jobs:
  include:
  - stage: Deploy
    script: echo "Deploying..."
    node_js: '8'
    deploy:
    - provider: script
      script: npm run gitpublish
      skip_cleanup: true
      on:
        branch: master
    - provider: npm
      skip_cleanup: true
      email: tobias@klemmer.info
      api_key:
        secure: ZIpW7a+/PXft00CrGyccoHQZ/u1vmMx87jHCUZQZBeNtFm09H/pnIMmGMmNh+KoCw/BzhEzOol+ek9rf5rDJEBvyWJps9bJAzeUn+s3RiPF0jf0Y24DX57BbVZsvrLx8iL90mTTpsV9eg7Eu3bdhVdEgRt1ATlrK3v4FMJcKenJ1Mnrh//Ion0c3YQcRcRMtwsbYQZ1EXk/h+EWcoM7SM5Kur2xsVTlK86j2dleg1N06ppF62UWdRK8SMAL7DTjC6BPMsedHei/fuLHKsHg4bfngUTg1xT+Hq9/Z451qtS6i2OCyomBplcUPp1uYWb/V//CUSA5hs0rIwgW9rioLXfQMdRy39h5a1gCc7c8yy+TvXBXhAEvcR8LTjcWYP3nrwd28zY0PuvC8MGPc6sSj64DDkI0NSojoqWcfObKsGpYvesqP95xHDLylBmBmUHxWot/61pca2txe7cQlJKb/PNyxkRZueXWsB28OA8G7VqtQ7lHY+iqyvSe+EFadzDWdX4lD/gZSU5IcFVEfpPEh7hvdXHnFC8CY1Q1cJ/2gka9J4HHOmqQ1cikaSgMjeeF7HALaHEP/LUKkjIbVnVOFYhNiT52uIdhS4i6GiZtF0t92gQ59G0xaOJ+0YSF3P8HBpA01aAvDpytDh4363fNL86V+Ex29F55mka/0a8ViHRg=
      on:
        tags: true
        branch: master
deploy:
  provider: npm
  email: tobias@klemmer.info
  api_key:
    secure: dcDCdT3Rzb9Jy+hvf+Z6Sdq0+rRCdJvEqzLAr7qAeeGIaH8p5wA8MouDNN9d3xt/rHTzl6LWIUl+/oNPqlgGkcCdfFivl62bh1GpI2qO4S6uo/BhEB9mV8T9PDNu2Ss+YL7P6VDAVdmRiTi4OR339uNHQf5HrEAjdvZe+T6BJowZ8NjwAZoyVMYi7ZXx1/iQJ2kAM+uwguNnRXgs3ewxua0T+QmQV7Aaa5PGqYzwqlC7fL4cPD1qzS6S8jSViJAdCm/aU3RFnmg9tn9y9rCevypIJsMVbTz1qJmt9gN2PgJdeSvGr9LLc6A+EiHiz6uwzoX1209M1MLonPT7cbY1wwqYySBbYOhFHhR5OI9C4C/OvTwrDjsYGIEbasG8Arng6d0ytfOLYpYwTrNWTqq6LEPj3Y70bKq9wPOxA++7US4HHD3ovjuZv33sellzOG8wMc9VR5dUOdKBW1Fvel9D5cMQteWfsRoZDkta9BLweMUigvFoLrbUfmPv9NxMu7yG5S2L14ykzHVPw/NweqwW34OR1RcKDNUh/jO++SUKf+li8MdxqkVAg/TJG+/ahWTKeb+thvb3LYDjPtdWfdaUgvxDrg0uYe3PBpYt7F66rD92jllaKRiepgmOL+h2uSQuEIZPMp0q+mtGBu4rN98iePhVmnWu3rG6D2c5pUsi8wY=
